### ISSUE TITLE
No messages seen in pyright lsp

### ISSUE THREAD

**Issue by Samyak2** [linrongbin16/lsp-progress.nvim#113]
## Description

When a python file is opened with the `pyright` lsp active, no progress messages are seen. The lsp works as intended though.

## Possible solutions

I see that [lsp-status.nvim](https://github.com/nvim-lua/lsp-status.nvim?tab=readme-ov-file#protocol-extensions) has extensions to support clangd and pyright. Are these implemented in `lsp-progress.nvim` too?

**Comment by linrongbin16** [comment]
hi @Samyak2, the two extensions for clangd and pyright are not implement.

but I don't think it's the root cause of no progress message. let me look into the  issue.

**Comment by Samyak2** [comment]
Oh sorry. I did not get any notifications for your updates.

I checked again and I'm seeing progress messages on larger projects - though it's reaching 100% very quickly and going way. I guess that just means pyright is pretty fast and I don't need to monitor the progress.

Thank you for the effort!
