### ISSUE TITLE
doesn't  work in some lsp

### ISSUE THREAD

**Issue by horaoen** [linrongbin16/lsp-progress.nvim#12]
I don't know why lsp-progress.nvim/fidget.nvim neither work in lua lsp

**Comment by linrongbin16** [comment]
please share some plugin config and setup in your `init.vim`/`init.lua`.

**Comment by horaoen** [comment]
this is my nvim repo config [plugins.lua](https://github.com/horaoen/nvim/blob/master/lua/plugins.lua)
More details are in my code repository.
neovim version: 0.9.

**Comment by linrongbin16** [comment]
Please setup autocmd to listen to `LspProgressStatusUpdated` event, and refresh lualine.

**Comment by horaoen** [comment]
> checking

sorry, I forgot loading nvim-lspconfig that's why some lsp not working. It’s my mistake to migrate from packer to lazy
