### ISSUE TITLE
Icon and spinner only in lualine

### ISSUE THREAD

**Issue by smartinellimarco** [linrongbin16/lsp-progress.nvim#126]
Hey there! First off, big thanks for the plugin.

Been using it for a bit and noticed the messages it shows are a bit too distracting for my liking. I'm mainly interested in knowing if any LSP is doing its thing (except copilot ofc), just to make sure everything's running smoothly. So, I tried to set up the plugin to work like this one: https://github.com/AndreM222/copilot-lualine/tree/main.

Here's the gist:
- If there are no LSPs attached, show a 'null' or 'block' emoji.
- If one or more LSPs are attached, show a 'tools' emoji with the count next to it.
- When an LSP is busy, switch the 'tools' emoji to a spinner until it's done.

I managed to get it working with this config:

```lua
local lsp_progress = require('lsp-progress')

lsp_progress.setup({
  spinner = { "⣾", "⣽", "⣻", "⢿", "⡿", "⣟", "⣯", "⣷" },
  client_format = function(_, spinner, series_messages)
    if #series_messages > 0 then
      return spinner
    else
      return nil
    end
  end,
  format = function(messages)
    local active_clients = vim.lsp.get_active_clients()
    -- Remove 'copilot' from active clients
    for i, client in ipairs(active_clients) do
      if client.name == "copilot" then
        table.remove(active_clients, i)
        break
      end
    end
    if #messages > 0 then
      return table.concat(messages, " ")
    end
    -- TODO: Display the disabled icon when...
    if #active_clients <= 0 then
      return ""
    else
      return ""
    end
  end,
})
```

However, there's a snag: The lualine component doesn't show up until the LSP client loads (I'm lazy loading it).
Also, I know from what I've read, that getting the LSP progress is costly. Is there any way to achieve this in a more efficient way, i.e without this plugin?

**Comment by linrongbin16** [comment]
hi @smartinellimarco,

To get active lsp clients (attached to current buufer), you can use `vim.api.get_active_clients`, see: https://github.com/linrongbin16/lsp-progress.nvim/blob/b673377c50ebaf37053f23cc3caeeb6d469ba1c1/lua/lsp-progress.lua#L255.

**Comment by linrongbin16** [comment]
I will try to improve the performance of this plugin's start time, actually I agree it takes a little bit more time to setup.

Now I am lazy load my heirline plugin on `VeryLazy`.

Also your config looks cool!

**Comment by linrongbin16** [comment]
Update:

I did some benchmark in #129 .

Record the time usage when initializing this plugin:
1. start at: https://github.com/linrongbin16/lsp-progress.nvim/pull/129/files#diff-cf57ad373fd0ad97d83dcf62d5e892444c4970f92e64b3b5a428856f1f9423c0R322
2. end at: https://github.com/linrongbin16/lsp-progress.nvim/pull/129/files#diff-cf57ad373fd0ad97d83dcf62d5e892444c4970f92e64b3b5a428856f1f9423c0R368
3. total used (milliseconds): https://github.com/linrongbin16/lsp-progress.nvim/pull/129/files#diff-cf57ad373fd0ad97d83dcf62d5e892444c4970f92e64b3b5a428856f1f9423c0R372

It shows only takes ~0.1 milliseconds:
 
<img width="600" alt="image" src="https://github.com/linrongbin16/lsp-progress.nvim/assets/6496887/3e37d34b-f3b5-4d72-9968-d508d29c7eec">

I'm benchmark it with latest nightly (nvim-0.10), so it should be super fast.

But on the other hand, I'm using this plugin with heirline.nvim, managed by lazy.nvim. The profile of lazy.nvim shows, it takes 4~5 milliseconds to start:

<img width="629" alt="image" src="https://github.com/linrongbin16/lsp-progress.nvim/assets/6496887/bf750fbc-c960-4bc8-9f35-31aeab403c3d">
