### ISSUE TITLE
Error with basic Lazy installation

### ISSUE THREAD

**Issue by igillis-clara** [linrongbin16/lsp-progress.nvim#132]
Before even incorportaing lsp-progress into lualine, I'm getting an error just configuring it with Lazy:

```
{
  "linrongbin16/lsp-progress.nvim",
  config = function()
    require("lsp-progress").setup()
  end,
}
```

gives
![CleanShot 2024-04-01 at 13 02 37@2x](https://github.com/linrongbin16/lsp-progress.nvim/assets/159797436/edeb4cd1-f8a9-40d2-9dde-3f564125f133)

**Comment by igillis** [comment]
It's just this line

```
      require('lsp-progress').setup()
```

Very strange. My understanding is that `require` returns `true` when the module you call it on doesn't return anything, but I'm not sure how that's possible.

**Comment by linrongbin16** [comment]
hi @igillis ,

can you share your nvim config's github repo? (if you use it to maintain your nvim config) I could take a look at it.

**Comment by igillis** [comment]
Good idea, it's here: https://github.com/igillis/neovim

I just pushed the commented out attempt I made at incorporating `lsp-progress`

**Comment by linrongbin16** [comment]
hi @igillis ,

the config looks good, but I found lualine doesn't depend on lsp-progress, check: https://github.com/igillis/neovim/blob/ab84d67cfeb26c4c95655414555ec497cde0ad23/lua/plugins/lualine.lua#L4

maybe add lsp-progress as lualine dependency, and try again.

**Comment by linrongbin16** [comment]
hi @igillis ,

This issue could be the same as #131 .

You can try setup lualine/lsp-progress with lazy like this:

```lua
lualine_c = {
    function()
        return require("lsp-progress").progress()
    end,
},
```

Note: use `function() ... end` to wrap the `progress` API, this can help avoid the lazy dependency issue.

**Comment by igillis** [comment]
Yes that fixed the error! Not showing anything in lualine just yet but that's presumably a different issue. 

Thanks -- feel free to close this out.
