### ISSUE TITLE
max_size setting causing errors with feline

### ISSUE THREAD

**Issue by KobraKommander9** [linrongbin16/lsp-progress.nvim#19]
Setting the max_size like so:
```lua
require('lsp-progress').setup({
  spinner = { '⣷', '⣯', '⣟', '⡿', '⢿', '⣻', '⣽', '⣾' },
  max_size = 40,
  client_format = function(client_name, spinner, series_messages)
    return #series_messages > 0
        and client_name ~= 'null-ls'
        and ('[' .. client_name .. '] ' .. spinner .. ' ' .. table.concat(
          series_messages,
          ', '
        ))
      or nil
  end,
})
```
causes errors when used with Feline:
`Feline: error while processing statusline component number 1 on section 2 of type 'active' for window 1000: Vim:E118: Too many arguments for function: max`

Full config [here](https://github.com/KobraKommander9/dot-files/tree/main/nvim/.config/nvim/lua/kobra/modules)

**Comment by linrongbin16** [comment]
Hi @KobraKommander9 ,
thanks for report, it's fixed in #20 , please update plugin and verify.
