### ISSUE TITLE
max_size still causing error

### ISSUE THREAD

**Issue by ls-devs** [linrongbin16/lsp-progress.nvim#25]
Hi,
Using max_size gives me errors, please see : 
![Capture d’écran 2023-06-14 à 14 46 13](https://github.com/linrongbin16/lsp-progress.nvim/assets/58638832/0ac8b11b-f6bb-42ae-accb-3c8e61bd3517)

Configuration : 
```lua
    function()
      return require("lsp-progress").progress({
        max_size = 40,
        format = function(messages)
          return #messages > 0 and table.concat(messages, " ") or ""
        end,
      })
    end,

```

**Comment by linrongbin16** [comment]
Hi @ls-devs , it could be a bug introduced in commit: https://github.com/linrongbin16/lsp-progress.nvim/commit/df2db65ac9bde2404ed810e09bbca3bd4421d928

I have revert this commit, please update and try.

**Comment by ls-devs** [comment]
> Hi @ls-devs , it could be a bug introduced in commit: [df2db65](https://github.com/linrongbin16/lsp-progress.nvim/commit/df2db65ac9bde2404ed810e09bbca3bd4421d928)
> 
> I have revert this commit, please update and try.

Hi @linrongbin16 ! Thank you for your fast reply.
Unfortunately,  even after update i'm still having this error ! 
I don't know if it can help but I use LSP Saga and the error appear when I use 
`Lspsaga diagnostic_jump_next`  only.

The error : 
![2023-06-15_08-20](https://github.com/linrongbin16/lsp-progress.nvim/assets/58638832/815f4907-4118-48b1-ba4c-6bc1a2e33414)

**Comment by linrongbin16** [comment]
I have tried your config in my lualine config, and it works good for me.

```
return require("lsp-progress").progress({
  max_size = 40,
  format = function(messages)
    return #messages > 0 and table.concat(messages, " ") or ""
  end,
}
```

Can you try to find where produced the `Illegal character <<e2>>`?

**Comment by ls-devs** [comment]
> 

Disabling LSP Saga solve the problem.
I don't know how to fix this I would really like to get both plugins working.

**Comment by linrongbin16** [comment]
...You can ask `Lspsaga` author, I'm not sure, maybe you can try to remove the icons?

**Comment by linrongbin16** [comment]
Oh, I also think that, you can try to remove all the icons in the default `series_format`, `client_format` and `format`.

**Comment by ls-devs** [comment]
> Oh, I also think that, you can try to remove all the icons in the default [series_format](https://github.com/linrongbin16/lsp-progress.nvim/blob/52bd3da14392c54a1b0dedf8ef81ee6628de9d6e/lua/lsp-progress/defaults.lua#L56), [client_format](https://github.com/linrongbin16/lsp-progress.nvim/blob/52bd3da14392c54a1b0dedf8ef81ee6628de9d6e/lua/lsp-progress/defaults.lua#L91) and [format](https://github.com/linrongbin16/lsp-progress.nvim/blob/52bd3da14392c54a1b0dedf8ef81ee6628de9d6e/lua/lsp-progress/defaults.lua#L109).
> 
> Maybe the icon fonts are not compatible.

It seems to be a good idea; but tbh I'm not really friendly with lua so I'm not sure how I am supposed to do it.

**Comment by ls-devs** [comment]
Hi @linrongbin16 ,
After some research, I tried to modify this  in your plugin : 
```lua
    if option.max_size >= 0 then
        if vim.fn.strdisplaywidth(content) > option.max_size then
            content = vim.fn.strcharpart(
                content,
                0,
                vim.fn.max({ option.max_size - 1, 0 })
            ) .. "…"
        end
    end
```

I switched `…` to `...` and the error changed from `Illegal character <<e2>> ` to `Illegal character <.>` and then I removed the line with
 ```lua
.. "..."
```
 and got  `Illegal character < >`

Is there something I can do with this ? Can the function `vim.fn.max` be the problem here ?

Please see the errors : 
![image](https://github.com/linrongbin16/lsp-progress.nvim/assets/58638832/a207bfca-2f22-4904-9d6c-6b40a61d8261)

![image](https://github.com/linrongbin16/lsp-progress.nvim/assets/58638832/d0623874-2237-4289-9cea-98da83ec5e35)

**Comment by ls-devs** [comment]
Found a solution,
Changed 
```lua 
if option.max_size >= 0 then
        if vim.fn.strdisplaywidth(content) > option.max_size then
            content = vim.fn.strcharpart(
                content,
                0,
                vim.fn.max({ option.max_size - 1, 0 })
            ) .. "…"
        end
    end
```
to : 
```lua
    if option.max_size >= 0 then
        if vim.fn.strdisplaywidth(content) > option.max_size then
            content = vim.fn.strcharpart(
                content,
                0,
                option.max_size
            ) .. "…"
        end
    end
```

**Comment by linrongbin16** [comment]
That's odd, this `strcharpart` should cut the `content` by length of `max_size - 1` (that is because I want to append an additional `…` at the end), but if the `max_size` is too small (for example 0 or 1), so I just use the max of `max_size-1` and `0`, so the length of this substring should always be a positive number.

In your use case, the `max_size=40`, then it should not be an issue. When the content `display width > 40`, then if should be cut to a 39 length string + `…`.

Oh, maybe there's unicode? So the string cut the byte?

**Comment by linrongbin16** [comment]
Can you give an example of language server progress message?

**Comment by ls-devs** [comment]
> Oh, maybe there's unicode? So the string cut the byte?

I think the problem comes from this too.





> Can you give an example of language server progress message?
Here's an example with code_action (where the errors come).

![image](https://github.com/linrongbin16/lsp-progress.nvim/assets/58638832/38e07d6f-3633-442f-9600-52653e8ed835)

**Comment by linrongbin16** [comment]
Can you share your nvim config repo, so I can try to see how do you use lsp-progress.nvim with Lspsaga? I still cannot re-produce your issue in my own environmeny

**Comment by ls-devs** [comment]
> Can you share your nvim config repo, so I can try to check how do you use lsp-progress.nvim with Lspsaga? I still cannot re-produce your issue in my own environmeny

Both plugins are not "linked" together, there's no configuration between LSP Saga and lsp-progress. They're just loaded like my others plugins.

You can find my config here : [https://github.com/ls-devs/nvim](ls-devs/nvim).
Branch is `lspprogress`

**Comment by linrongbin16** [comment]
thanks, I will try

**Comment by ls-devs** [comment]
> thanks, I will try

Maybe there's something to do with my terminal and my font ? I use Kitty and FiraCode Nerd Font.

**Comment by linrongbin16** [comment]
ok, got it haha

**Comment by linrongbin16** [comment]
I'm sorry, I didn't found lsp-progress plugin installed in your https://github.com/ls-devs/nvim.

**Comment by ls-devs** [comment]
@linrongbin16 My bad. I merged all my modifications to main. You can pull and try now. Let me know if u still have a problem but u should be fine.

**Comment by linrongbin16** [comment]
Sorry I will be on chinese holiday tomorrow, still not debugging your config.

But I create a temporary [fix branch](https://github.com/linrongbin16/lsp-progress.nvim/tree/fix/max) for you, you can try that.

After the holiday, I will do it.

**Comment by linrongbin16** [comment]
Hi @ls-devs ,

I checked the latest main branch of your config, looks like you have already removed `lsp-progress`. So I searched your commit log and tried this commit: https://github.com/ls-devs/nvim/commit/445f0ce48a0c5c66ea17592fae01b818964985aa.

Since I only tried it in a few lua files, the message string length is not so long, so I set `max_size=10`, but no error throwed.

So please give me a more clear file and lsp list, that are easier to re-produce this issue, if you still want to use `lsp-progress`.

Thanks

**Comment by linrongbin16** [comment]
BTW, your [ls-dev/nvim](https://github.com/ls-devs/nvim) is really cool!

**Comment by daephx** [comment]
I just started trying out this plugin and I am experiencing something related to this issue.
The client message im monitoring is lua_ls while it loads two workspaces on startup,
so my message output looks something like this:

```plain
[lua_ls] ⡿ Loading workspace 198/2497 (7%), Loading workspace 195/2500 (7%)
```

I'm unsure of this is actually what is happening, just an assumption based on observation.

For my setup, there are no errors at first until the loading progresses further. An error will only occur when the length of the message string grows and transits the `max_size` threshold.

So, if the client message starts off at ~72 characters in length and the `max_size` is set to 80, than as the loading/percentage values increase, the message will grow by a few characters until it eventually is greater than or equal to `max_size`; at which point, it will raise multiple errors until it settles back down to a smaller message length.

Any shorter messages such as `[null-ls] ⣟ formatting stylua (100%) - done` do not raise any errors.

**Comment by linrongbin16** [comment]
I will try to fix it

**Comment by linrongbin16** [comment]
Hi @daephx , I fixed this issue in https://github.com/linrongbin16/lsp-progress.nvim/pull/64, please pull latest main branch and try again.

**Comment by daephx** [comment]
@linrongbin16 Awesome! I'm no longer getting the error with the new patch.
Good work, I'll update if there are anymore errors.

Thanks!

**Comment by linrongbin16** [comment]
Thanks for your reporting!

**Comment by daephx** [comment]
Alright, so there is no error on startup when sitting and simply watching the progress.
But I started a fresh instance of neovim and attempted to write the active buffer before lua_ls finished loading the workspaces. Writing the buffer triggered null-ls to call stylua, which probably added to the messages that lsp-progress has to handle and triggered the error to occur once again.

<details>
<summary>Error traceback for clarity.</summary>

```plain
Error executing vim.schedule lua callback: vim/_editor.lua:0: nvim_exec2()..User Autocommands for "*": Vim(append):Error executing lua callback: ...e/nvim/lazy/lualine.nvim/lua/lualine/utils/nvim_opts.lua:77: E539
: Illegal character <<e2>>
stack traceback:
        [C]: in function 'nvim_win_set_option'
        ...e/nvim/lazy/lualine.nvim/lua/lualine/utils/nvim_opts.lua:77: in function 'setter_fn'
        ...e/nvim/lazy/lualine.nvim/lua/lualine/utils/nvim_opts.lua:50: in function 'set_opt'
        ...e/nvim/lazy/lualine.nvim/lua/lualine/utils/nvim_opts.lua:74: in function 'set'
        ...ephx/.local/share/nvim/lazy/lualine.nvim/lua/lualine.lua:435: in function <...ephx/.local/share/nvim/lazy/lualine.nvim/lua/lualine.lua:321>
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        ...e/nvim/lazy/lsp-progress.nvim/lua/lsp-progress/event.lua:92: in function 'emit'
        ...l/share/nvim/lazy/lsp-progress.nvim/lua/lsp-progress.lua:236: in function 'progress_handler'
        ...l/share/nvim/lazy/lsp-progress.nvim/lua/lsp-progress.lua:311: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1149: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        ...e/nvim/lazy/lsp-progress.nvim/lua/lsp-progress/event.lua:92: in function 'emit'
        ...l/share/nvim/lazy/lsp-progress.nvim/lua/lsp-progress.lua:236: in function 'progress_handler'
        ...l/share/nvim/lazy/lsp-progress.nvim/lua/lsp-progress.lua:311: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1149: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

</details>

**Comment by linrongbin16** [comment]
Hi @daephx , using your minimal init, I got this error (on ubuntu LTS-22.04):


![image](https://github.com/linrongbin16/lsp-progress.nvim/assets/6496887/0a9f3d4f-909c-41eb-815a-cba28c800c98)

But I didn't get the error you posted.

**Comment by linrongbin16** [comment]
I modified your minimal init lua file:

```lua


```

And it's working now:

![image](https://github.com/linrongbin16/lsp-progress.nvim/assets/6496887/2418d1a1-32ba-471e-811a-1a83336a78d2)


Somehow I still didn't know where this error happens, please carefully update the init lua file.

**Comment by daephx** [comment]
Admittedly, I overlooked a few things and jumped to a fresh computer system to verify.
Sorry for the trouble. I don't think mason accepts `ensure_install` on it's own. The `mason-lspconfig` and `mason-null-ls` compatibility plugins handle that in my config.

I updated the init file, hopefully this works.

<details>
<summary><code>repro.lua</code></summary>

```lua
-- repro.lua: Minimal reproducible config for debugging neovim plugins
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  { -- Initialize language server configuration
    "neovim/nvim-lspconfig",
    cmd = { "LspInfo", "LspInstall", "LspUninstall" },
    event = { "BufReadPost", "BufNewFile" },
    dependencies = {
      { -- Portable package manager for Neovim
        "williamboman/mason.nvim",
        opts = { ensure_installed = { "stylua" } },
      },
      -- Neovim setup for init.lua and plugin development
      { "folke/neodev.nvim", config = true },
    },
    config = function()
      require("lspconfig")["lua_ls"].setup({
        settings = {
          Lua = {
            diagnostics = {
              enable = true,
              groupSeverity = {
                strong = "Warning",
                strict = "Warning",
              },
              groupFileStatus = {
                ["ambiguity"] = "Opened",
                ["await"] = "Opened",
                ["codestyle"] = "None",
                ["duplicate"] = "Opened",
                ["global"] = "Opened",
                ["luadoc"] = "Opened",
                ["redefined"] = "Opened",
                ["strict"] = "Opened",
                ["strong"] = "None",
                ["type-check"] = "Opened",
                ["unbalanced"] = "Opened",
                ["unused"] = "Opened",
              },
              disable = {
                "incomplete-signature-doc",
                "lowercase-global",
              },
              globals = { "vim" },
              unusedLocalExclude = { "_*" },
            },
            format = {
              enable = false,
              defaultConfig = {
                indent_size = "2",
                continuation_indent = "2",
                indent_style = "space",
                max_line_length = "80",
                quote_style = "double",
                insert_final_newline = "true",
                trim_trailing_whitespace = "true",
              },
            },
            workspace = {
              checkThirdParty = false,
            },
          },
        },
      })
    end,
  },
  { -- Use Neovim as a language server
    "jose-elias-alvarez/null-ls.nvim",
    event = { "BufReadPost", "BufNewFile" },
    dependencies = {
      -- Collection of useful lua functions
      { "nvim-lua/plenary.nvim" },
    },
    config = function()
      local nls = require("null-ls")
      nls.setup({
        sources = {
          nls.builtins.formatting.stylua.with({
            condition = function(utils)
              return utils.root_has_file({ "stylua.toml", ".stylua.toml" })
            end,
          }),
        },
      })
    end,
  },
  {
    "williamboman/mason-lspconfig.nvim",
    dependencies = {
      "williamboman/mason.nvim",
      "neovim/nvim-lspconfig",
    },
    opts = { ensure_installed = { "lua_ls" } },
  },
  {
    "jayp0521/mason-null-ls.nvim",
    dependencies = {
      "williamboman/mason.nvim",
      "jose-elias-alvarez/null-ls.nvim",
    },
    opts = { ensure_installed = { "stylua" } },
  },
  {
    "nvim-lualine/lualine.nvim",
    event = "UIEnter",
    dependencies = {
      -- Lua fork of vim-web-devicons for neovim
      { "nvim-tree/nvim-web-devicons" },
      -- A performant lsp progress status for Neovim.
      { "linrongbin16/lsp-progress.nvim", config = true },
    },
    config = function(_, opts)
      require("lualine").setup(opts)

      vim.api.nvim_create_autocmd("User LspProgressStatusUpdated", {
        desc = "listen lsp-progress event and refresh lualine",
        group = vim.api.nvim_create_augroup("lualine_augroup", { clear = true }),
        callback = require("lualine").refresh,
      })
    end,
    opts = {
      sections = {
        lualine_a = { "mode" },
        lualine_b = {},
        lualine_c = { "filename" },
        lualine_x = {
          { -- Setup lsp-progress component
            function()
              return require("lsp-progress").progress({
                max_size = 80,
                format = function(messages)
                  local active_clients = vim.lsp.get_clients({ bufnr = 0 })
                  if #messages > 0 then
                    return table.concat(messages, " ")
                  end
                  local client_names = {}
                  for _, client in ipairs(active_clients) do
                    if client and client.name ~= "" then
                      table.insert(client_names, 1, client.name)
                    end
                  end
                  return table.concat(client_names, "  ")
                end,
              })
            end,
            icon = { "", align = "right" },
          },
          "diagnostics",
        },
        lualine_y = { "filetype", "encoding", "fileformat" },
        lualine_z = { "location" },
      },
      tabline = {
        lualine_a = {
          function()
            return ""
          end,
        },
        lualine_b = { "windows" },
        lualine_y = { "tabs" },
        lualine_z = {
          function()
            return ""
          end,
        },
      },
    },
  },
}

-- Attach autocmd to enable auto-formatting on save
vim.api.nvim_create_autocmd({ "LspAttach" }, {
  callback = function(ev)
    -- Apply autocmd if client supports formatting
    vim.api.nvim_create_autocmd("BufWritePre", {
      buffer = ev.buf,
      desc = "Apply Auto-formatting for to document on save",
      group = vim.api.nvim_create_augroup("LspFormat." .. ev.buf, {}),
      callback = function()
        vim.lsp.buf.format({
          bufnr = ev.buf,
          filter = function(client)
            return client.name == "null-ls"
          end,
        })
      end,
    })
  end,
})

-- Setup lazy.nvim
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

</details>

As for the other error from lua_ls, I got that as well and it might be trying to read the lua-language-server as part of the workspace. Seems inconsequential since it's a non-blocking error and I still get the Illegal character error along side it.

```
LSP[lua_ls][Info] Too large file: .repro/data/nvim/mason/packages/lua-language-server/libexec/meta/default utf8/UnityEngine.lua skipped. The currently
set size limit is: 500 KB, and the file size is: 2521.24 KB.
```

Reproduction steps:

It is inconsistent and only occurs every 2-5 reloads of neovim using the following steps

1. Open repro.lua via `nvim -u repro.lua`
2. Open a lua file to allow lsp to attach
3. spam `:w` as the language server loads
4. If you did not get in error by the time it finishes, repeat from step 1

**Comment by daephx** [comment]
Hmm, honestly using your init doesn't give me an error.
I noticed you removed the `format` option from lsp-progress.progress and that gets rid of the issue if my init as well...

Though my format is only a slight modification of the one provided by the wiki [Advanced-Configuration](https://github.com/linrongbin16/lsp-progress.nvim/wiki/Advanced-Configuration).

**Comment by linrongbin16** [comment]
Hi @daephx ,

1. I submit another PR #66 to use 'pcall' on configured 'format' function and improve the error message.
2. I tried again with the 'format' function from the minimal init lua that you provided, it's working now:

minimal init.lua
```lua
local root = vim.fn.stdpath("data")

-- bootstrap lazy
local lazypath = root .. "/lazy/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    { -- Initialize language server configuration
        "neovim/nvim-lspconfig",
        cmd = { "LspInfo", "LspInstall", "LspUninstall" },
        event = { "BufReadPost", "BufNewFile" },
        dependencies = {
            { "williamboman/mason.nvim", config = true },
            { "folke/neodev.nvim", config = true },
        },
        config = function()
            require("lspconfig")["lua_ls"].setup({
                settings = {
                    Lua = {
                        diagnostics = {
                            enable = true,
                            globals = { "vim" },
                        },
                        workspace = {
                            checkThirdParty = false,
                        },
                    },
                },
            })
        end,
    },
    {
        "jose-elias-alvarez/null-ls.nvim",
        event = { "BufReadPost", "BufNewFile" },
        dependencies = { "nvim-lua/plenary.nvim" },
        config = function()
            local null_ls = require("null-ls")
            null_ls.setup({
                sources = { null_ls.builtins.formatting.stylua },
            })
        end,
    },
    {
        "nvim-lualine/lualine.nvim",
        event = "UIEnter",
        dependencies = {
            -- Lua fork of vim-web-devicons for neovim
            { "nvim-tree/nvim-web-devicons" },
            -- A performant lsp progress status for Neovim.
            {
                "linrongbin16/lsp-progress.nvim",
                config = true,
                -- dev = true,
                -- dir = "~/github/linrongbin16/lsp-progress.nvim",
            },
        },
        config = function(_, opts)
            require("lualine").setup(opts)

            vim.api.nvim_create_augroup("lualine_augroup", { clear = true })
            vim.api.nvim_create_autocmd("User LspProgressStatusUpdated", {
                group = "lualine_augroup",
                callback = require("lualine").refresh,
            })
        end,
        opts = {
            sections = {
                lualine_a = { "mode" },
                lualine_b = {},
                lualine_c = { "filename" },
                lualine_x = {
                    { -- Setup lsp-progress component
                        function()
                            return require("lsp-progress").progress({
                                max_size = 80,
                                format = function(messages)
                                    local active_clients =
                                        vim.lsp.get_active_clients()
                                    if #messages > 0 then
                                        return table.concat(messages, " ")
                                    end
                                    local client_names = {}
                                    for _, client in ipairs(active_clients) do
                                        if client and client.name ~= "" then
                                            table.insert(
                                                client_names,
                                                1,
                                                client.name
                                            )
                                        end
                                    end
                                    return table.concat(client_names, "  ")
                                end,
                            })
                        end,
                        icon = { "", align = "right" },
                    },
                    "diagnostics",
                },
                lualine_y = { "filetype", "encoding", "fileformat" },
                lualine_z = { "location" },
            },
        },
    },
}

-- Attach autocmd to enable auto-formatting on save
vim.api.nvim_create_autocmd({ "LspAttach" }, {
    callback = function(ev)
        -- Apply autocmd if client supports formatting
        vim.api.nvim_create_autocmd("BufWritePre", {
            buffer = ev.buf,
            desc = "Apply Auto-formatting for to document on save",
            group = vim.api.nvim_create_augroup("LspFormat." .. ev.buf, {}),
            callback = function()
                vim.lsp.buf.format({
                    bufnr = ev.buf,
                    filter = function(client)
                        return client.name == "null-ls"
                    end,
                })
            end,
        })
    end,
})

-- Setup lazy.nvim
require("lazy").setup(plugins, {
    root = root .. "/lazy/plugins",
})

```

Here's the screen recording I made on my Windows 10 x86_64 bit, with Neovim v0.9.2 and latest plugins.

https://github.com/linrongbin16/lsp-progress.nvim/assets/6496887/fb72ead8-857b-4511-9c30-979131fe5082

**Comment by daephx** [comment]
> 2. I tried again with the 'format' function from the minimal init lua that you provided, it's working now:

By this, do you mean: reintroducing the `format` function allows you to reproduce the error?

Sadly I can't say that this new patch has fixed the situation in my main config.

https://github.com/linrongbin16/lsp-progress.nvim/assets/36192863/325ae44b-06b1-43ba-b087-f57fa29593bd
