### ISSUE TITLE
Output messages from clients only in buffers they attached to

### ISSUE THREAD

**Issue by AlexKurisu** [linrongbin16/lsp-progress.nvim#67]
Is it possible to make lsp-progress output messages from LSP clients only to statuslines which window's buffer has those LSP clients attached? For example, if you open python file and Lua file, it should output messages from lua-ls only to statusline for lua file and not python file

**Comment by daephx** [comment]
You can try something like this using the client_format options.

```lua
return {
  "linrongbin16/lsp-progress.nvim",
  opts = {
    client_format = function(client_name, spinner, series_messages)
      local active_clients = vim.tbl_map(function(client)
        return client.name
      end, vim.lsp.get_active_clients({ bufnr = 0 }))
      if #series_messages > 0 and vim.tbl_contains(active_clients, client_name) then
        local messages = table.concat(series_messages, ", ")
        return ("[%s] %s %s"):format(client_name, spinner, messages)
      end
    end,
  },
}
```

**Comment by linrongbin16** [comment]
emmm, I didn't filter lsp messages use current buffer's filetype.

But I found I never met such an issue, that python lsp gives me any message when I am editing a lua file?
