### ISSUE TITLE
E539: Illegal character <i> when opening neovide code base with rust analyzer

### ISSUE THREAD

**Issue by linrongbin16** [linrongbin16/lsp-progress.nvim#98]
<img width="1728" alt="image" src="https://github.com/linrongbin16/lsp-progress.nvim/assets/6496887/0cf3c9ff-f71e-4c10-890a-a63de04e2eaf">

It may relate to #95 .

**Comment by linrongbin16** [comment]
emmmm, it seems an issue from lualine, reported here: https://github.com/nvim-lualine/lualine.nvim/issues/1136.

**Comment by linrongbin16** [comment]
<img width="751" alt="image" src="https://github.com/linrongbin16/lsp-progress.nvim/assets/6496887/b4c144b2-39df-432c-9c1e-c0b1bf1799b6">


based on vim doc, `vim.pesc()` could escape all the lua pattern characters, it is the root cause of this issue, the wrong characters are: `<d>`, `<+>`, etc.

**Comment by linrongbin16** [comment]
We should only replace the `%` char to `%%`, not use this `vim.pesc()` API.

**Comment by cuducos** [comment]
> we should only replace the `%` char to `%%`, not use `vim.pesc()` API.

My bad, sorry.

> since I'm not expert on ruby, would you please help confirm if this PR can work correctly in your project?

Just tested, head is at af46da3 — all working beautifully! Thank you so much : )

**Comment by linrongbin16** [comment]
thanks for your help!

**Comment by cuducos** [comment]
I am sorry but it looks like I rushed into conclusions. This error is back:

```
Error executing vim.schedule lua callback: vim/_editor.lua:0: nvim_exec2()..User Autocommands for "LspProgressStatusUpdated": Vim(append):Error executing lua callback: ...e/nvim/lazy/lualin
e.nvim/lua/lualine/utils/nvim_opts.lua:77: E539: Illegal character < >
```

I haven't had time to debug, but will try to do it later.

**Comment by linrongbin16** [comment]
I think you're right in the first PR, the Neovim statusline itself also format the percentage `%`.... I didn't really pay attention at first.

**Comment by cuducos** [comment]
So, it looks like the we're not escaping the `%`… I see the value being sent by Lualine to be:

```
ERROR setting option statusline to: %#lualine_a_normal# NORMAL %#lualine_transitional_lualine_a_normal_to_lualine_b_normal#%#lualine_b_normal#  sdp-migration/low-install-checks-to-prod %#lualine_transitional_lualine_b_normal_to_lualine_c_filetype_DevIconRb_normal#%<%#lualine_c_filetype_DevIconRb_normal# %#lualine_c_normal# ruby %#lualine_c_normal#%#lualine_c_normal#  app/jobs/trust_automation/install_check_ingestion_job.rb %#lualine_c_normal#%=%#lualine_c_normal#  LSP [ruby_ls] ⣷ Ruby LSP: indexing files 100% completed (100%%) - done %#lualine_c_normal#  %#lualine_c_normal# utf-8 %#lualine_transitional_lualine_a_normal_to_lualine_c_normal#%#lualine_a_normal#   6:1  %#lualine_a_normal# 16%% 
```

Again we have one unescaped `%` in ` Ruby LSP: indexing files 100% completed (100%%)`


I see #104 removed the `gsub` from `series-format` and has not included it into `client_format` — was that intentional?

**Comment by linrongbin16** [comment]
in #103 , I was thinking we don't need to double the `%` chars, because in `client_format` I removed the `string.format` API (that will render/consume 1 `%` from `%%`), instead I use `..` to append string, so the lsp progress content should not be modified.

**Comment by cuducos** [comment]
Hum… got it! Yes, we might need it, I guess. Because (as far as I got) the `%` has is a special character for Neovim's statusline, winbar etc.

**Comment by linrongbin16** [comment]
oh I got it, so we really need to double the `%` chars, just like the `string.format("(%.0f%%%%)", percentage)`.

**Comment by linrongbin16** [comment]
@cuducos would you please help test on this branch: `fix-percentage-again` ( #105 ) ?

**Comment by cuducos** [comment]
Tested. Works like a charm ✨

**Comment by linrongbin16** [comment]
really thank you for working with my on this issue! I merged it to main branch.
